format = """
$directory$git_branch\
$nodejs\
$python\
$golang\
$java\
$cmd_duration\
$character
"""

[directory]
style = "blue"
read_only = " "
truncation_length = 1
truncate_to_repo = true

[git_branch]
symbol = " "
format = "[$symbol $branch]($style) "
style = "bright-black"

[git_status]
disabled = true

[git_metrics]
disabled = true

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"
style = "green"
disabled = false

[python]
symbol = " "
format = "[$symbol($version )(\\($virtualenv\\) )]($style)"
style = "yellow"
disabled = false

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style = "cyan"
disabled = false

[java]
symbol = " "
format = "[$symbol($version )]($style)"
style = "bright-red"
disabled = false

[cmd_duration]
min_time = 3000
format = "[$duration]($style) "
style = "yellow"

[character]
success_symbol = "[❯](bright-black)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bright-black)"
